USE [KutuphaneDB]
GO

/****** Object:  Table [dbo].[Katlar]    Script Date: 17.12.2025 22:40:35 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Katlar](
	[KatID] [int] NOT NULL,
	[Ad] [nvarchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[KatID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

