USE [KutuphaneDB]
GO

/****** Object:  Table [dbo].[RolYetkileri]    Script Date: 17.12.2025 22:43:41 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[RolYetkileri](
	[YetkiID] [int] IDENTITY(1,1) NOT NULL,
	[RolID] [int] NOT NULL,
	[IslemAdi] [nvarchar](50) NOT NULL,
	[YetkiliMi] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[YetkiID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_RolYetki] UNIQUE NONCLUSTERED 
(
	[RolID] ASC,
	[IslemAdi] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[RolYetkileri] ADD  DEFAULT ((0)) FOR [YetkiliMi]
GO

ALTER TABLE [dbo].[RolYetkileri]  WITH CHECK ADD FOREIGN KEY([RolID])
REFERENCES [dbo].[Roller] ([RolID])
GO

