USE [KutuphaneDB]
GO

/****** Object:  Table [dbo].[MenuDetaylari]    Script Date: 17.12.2025 22:41:52 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MenuDetaylari](
	[DetayID] [int] IDENTITY(1,1) NOT NULL,
	[MenuID] [int] NULL,
	[UrunID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[DetayID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_MenuDetaylari_Menu_Urun] UNIQUE NONCLUSTERED 
(
	[MenuID] ASC,
	[UrunID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[MenuDetaylari]  WITH CHECK ADD FOREIGN KEY([MenuID])
REFERENCES [dbo].[Menuler] ([MenuID])
GO

ALTER TABLE [dbo].[MenuDetaylari]  WITH CHECK ADD FOREIGN KEY([UrunID])
REFERENCES [dbo].[KafeUrunleri] ([UrunID])
GO

